# Generated by Django 4.2.18 on 2026-08-01 08:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0002_blog_enabled"),
    ]

    operations = [
        migrations.CreateModel(
            name="Comments",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("text", models.TextField()),
                ("blog_id", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="blog.blog")),
            ],
        ),
    ]
