# Generated by Django 4.2.18 on 2026-08-01 08:54

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0003_comments"),
    ]

    operations = [
        migrations.RenameField(
            model_name="comments",
            old_name="blog_id",
            new_name="blog",
        ),
    ]
