# Generated by Django 4.2.18 on 2026-08-01 12:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0004_rename_blog_id_comments_blog"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comments",
            name="blog",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comments",
                to="blog.blog",
            ),
        ),
    ]
